import { execSync } from "child_process";
import {
  ensureGitRepo,
  resolveRef,
  getCommitsInclusive,
  getFullCommitDiffs,
  estimateDiffTokens,
  splitDiffByFile,
  chunkFileDiffs,
  type CommitInfo,
  type FileDiff,
} from "../git.js";
import {
  CODE_REVIEW_SYSTEM_PROMPT,
  CODE_REVIEW_CHUNK_SYSTEM_PROMPT,
  CODE_REVIEW_MERGE_SYSTEM_PROMPT,
  buildCodeReviewUserMessage,
  buildChunkedReviewMergeMessage,
} from "../prompt.js";
import { callLlm, getModelContextWindow, type LlmOptions } from "../llm.js";
import {
  buildReviewHeader,
  resolveOutputPath,
  writeOutputFile,
} from "../output.js";

// ---------------------------------------------------------------------------
// GitHub PR review
// ---------------------------------------------------------------------------

export interface GitHubPrReviewOptions extends LlmOptions {
  prRef: string;
  save?: boolean;
  output?: string;
}

/**
 * Returns a normalized gh-compatible PR ref (URL or number string) if the
 * input looks like a GitHub PR reference, otherwise null.
 * Accepts: full URLs, bare numbers ("550"), or hash-prefixed numbers ("#550").
 */
export function parseGitHubPrRef(
  ref: string
): string | null {
  if (/github\.com\/[^/]+\/[^/]+\/pull\/\d+/.test(ref)) return ref;
  if (/^#?\d+$/.test(ref)) return ref.replace(/^#/, "");
  return null;
}

function gh(args: string): string {
  try {
    return execSync(`gh ${args}`, {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
  } catch (err: any) {
    const stderr = err.stderr?.toString().trim() || err.message;
    throw new Error(`gh ${args.split(" ")[0]} failed: ${stderr}`);
  }
}

/**
 * Run a chunked review: review file groups separately, then merge results.
 */
async function runChunkedReview(
  chunks: FileDiff[][],
  contextDescription: string,
  options: LlmOptions
): Promise<string> {
  const partialReviews: { chunkIndex: number; fileList: string[]; review: string }[] = [];

  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    const fileList = chunk.map((f) => f.filePath);
    const combinedDiff = chunk.map((f) => f.diff).join("\n\n");

    console.error(`Reviewing chunk ${i + 1}/${chunks.length} (${chunk.length} files)...`);
    if (options.verbose) {
      for (const f of fileList) {
        console.error(`  - ${f}`);
      }
    }

    const chunkMessage = `${contextDescription}

This is chunk ${i + 1} of ${chunks.length} — reviewing the following files:
${fileList.map((f) => `- ${f}`).join("\n")}

## Diff:
\`\`\`diff
${combinedDiff}
\`\`\`

Provide a thorough code review of these files.`;

    const chunkResult = await callLlm(
      CODE_REVIEW_CHUNK_SYSTEM_PROMPT,
      chunkMessage,
      { ...options, silent: true }
    );

    partialReviews.push({
      chunkIndex: i,
      fileList,
      review: chunkResult.content,
    });
  }

  // Merge partial reviews
  console.error(`Merging ${partialReviews.length} partial reviews...`);
  const mergeMessage = buildChunkedReviewMergeMessage(partialReviews);
  const mergeResult = await callLlm(
    CODE_REVIEW_MERGE_SYSTEM_PROMPT,
    mergeMessage,
    options
  );

  return mergeResult.content;
}

export async function reviewGitHubPrCommand(
  options: GitHubPrReviewOptions
): Promise<void> {
  const prRef = options.prRef;

  if (options.verbose) {
    console.error(`Fetching PR ${prRef} via gh...`);
  }

  // Fetch PR metadata via gh (works for URLs and numbers alike)
  const metaJson = gh(
    `pr view ${prRef} --json number,title,body,author,baseRefName,headRefName,url`
  );
  const meta = JSON.parse(metaJson) as {
    number: number;
    title: string;
    body: string;
    author: { login: string };
    baseRefName: string;
    headRefName: string;
    url: string;
  };

  // Get owner/repo from the resolved PR URL (e.g. https://github.com/owner/repo/pull/N)
  const urlMatch = meta.url.match(/github\.com\/([^/]+)\/([^/]+)\/pull\//);
  const repoDisplay = urlMatch ? `${urlMatch[1]}/${urlMatch[2]}` : "";

  // Fetch diff via gh
  const diff = gh(`pr diff ${prRef}`);

  const today = new Date().toISOString().split("T")[0];
  const header = `# Code Review: PR #${meta.number} — ${meta.title}

> **Repo:** ${repoDisplay}
> **Author:** ${meta.author?.login ?? "unknown"}
> **PR URL:** ${meta.url}
> **Base → Head:** \`${meta.baseRefName}\` → \`${meta.headRefName}\`
> Generated by git-genie on ${today}

`;

  const estimatedTokens = Math.ceil(diff.length / 4);
  const contextWindow = getModelContextWindow(options.provider, options.model);
  // Reserve ~40% for system prompt + response
  const availableTokens = Math.floor(contextWindow * 0.6);

  if (options.verbose) {
    console.error(`Estimated diff size: ~${Math.round(estimatedTokens / 1000)}k tokens (${Math.round(availableTokens / 1000)}k available)`);
    console.error("");
  }

  process.stdout.write(header);

  let reviewContent: string;

  if (estimatedTokens > availableTokens) {
    // Chunked review
    const files = splitDiffByFile(diff);
    const chunks = chunkFileDiffs(files, availableTokens);

    console.error(
      `Diff too large for single request (~${Math.round(estimatedTokens / 1000)}k tokens). Splitting into ${chunks.length} chunks...`
    );

    const contextDescription = `Review the following files from GitHub Pull Request #${meta.number}: ${meta.title}
**Author:** ${meta.author?.login ?? "unknown"}
**Description:**
${meta.body || "(no description)"}`;

    reviewContent = await runChunkedReview(chunks, contextDescription, options);
  } else {
    // Single review
    const userMessage = `Review the following GitHub Pull Request:

## PR #${meta.number}: ${meta.title}
**Author:** ${meta.author?.login ?? "unknown"}
**Description:**
${meta.body || "(no description)"}

## Diff:
\`\`\`diff
${diff}
\`\`\`

Provide a thorough code review.`;

    const result = await callLlm(CODE_REVIEW_SYSTEM_PROMPT, userMessage, options);
    reviewContent = result.content;
  }

  if (options.save || options.output) {
    const outputPath =
      options.output ?? `notes/review-${today}-pr${meta.number}.md`;
    writeOutputFile(outputPath, header + reviewContent);
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ReviewOptions extends LlmOptions {
  startRef: string;
  endRef?: string;
  save?: boolean;
  output?: string;
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export async function reviewCommand(options: ReviewOptions): Promise<void> {
  ensureGitRepo();

  // Resolve refs
  const startRefInfo = resolveRef(options.startRef);
  const endRefInfo = options.endRef
    ? resolveRef(options.endRef)
    : null;

  // Get commits
  let commits: CommitInfo[];

  if (endRefInfo) {
    // Range: inclusive of both endpoints
    commits = getCommitsInclusive(options.startRef, options.endRef!);
  } else {
    // Single commit
    commits = [
      {
        hash: startRefInfo.hash,
        shortHash: startRefInfo.hash.substring(0, 6),
        author: "", // Will be filled from git show
        date: "",
        subject: "",
        body: "",
      },
    ];

    // Get the actual commit info
    try {
      const info = execSync(
        `git log -1 --format="%an%n%ad%n%s%n%b" "${startRefInfo.hash}"`,
        { encoding: "utf-8" }
      ).trim();
      const lines = info.split("\n");
      commits[0].author = lines[0] || "";
      commits[0].date = lines[1] || "";
      commits[0].subject = lines[2] || "";
      commits[0].body = lines.slice(3).join("\n").trim();
    } catch {
      // Continue with empty metadata — the diff is what matters
    }
  }

  if (commits.length === 0) {
    console.error("No commits found in the specified range.");
    process.exit(1);
  }

  if (options.verbose) {
    const rangeDesc = endRefInfo
      ? `${startRefInfo.displayName}..${endRefInfo.displayName}`
      : startRefInfo.displayName;
    console.error(`Reviewing ${commits.length} commit(s): ${rangeDesc}`);
    console.error("Collecting diffs...");
    console.error("");
  }

  // Check if total diff size fits in context window
  const estimatedTokens = estimateDiffTokens(commits);
  const contextWindow = getModelContextWindow(options.provider, options.model);
  // Reserve ~40% for system prompt + response
  const availableTokens = Math.floor(contextWindow * 0.6);

  if (options.verbose) {
    console.error(
      `Estimated diff size: ~${Math.round(estimatedTokens / 1000)}k tokens (${Math.round(availableTokens / 1000)}k available)`
    );
    console.error("");
  }

  // Get full diffs (no truncation for review)
  const commitDiffs = getFullCommitDiffs(commits);

  // Build header
  const header = buildReviewHeader(
    startRefInfo,
    endRefInfo,
    commits.length
  );

  // Determine output path
  const targetRef = endRefInfo || startRefInfo;
  const outputPath = resolveOutputPath(
    { save: options.save, output: options.output },
    "review",
    targetRef
  );

  // Print header
  process.stdout.write(header);

  let reviewContent: string;

  if (estimatedTokens > availableTokens) {
    // Chunked review: split all commit diffs by file and chunk
    const allPatches = commitDiffs.map((c) => c.patch).join("\n\n");
    const files = splitDiffByFile(allPatches);
    const chunks = chunkFileDiffs(files, availableTokens);

    console.error(
      `Diff too large for single request (~${Math.round(estimatedTokens / 1000)}k tokens). Splitting into ${chunks.length} chunks...`
    );

    const rangeDesc = endRefInfo
      ? `${startRefInfo.displayName}..${endRefInfo.displayName}`
      : startRefInfo.displayName;

    const contextDescription = `Review the following files from commit(s) ${rangeDesc} (${commits.length} total commits).`;

    reviewContent = await runChunkedReview(chunks, contextDescription, options);
  } else {
    // Single review
    const userMessage = buildCodeReviewUserMessage(commitDiffs);
    const result = await callLlm(
      CODE_REVIEW_SYSTEM_PROMPT,
      userMessage,
      options
    );
    reviewContent = result.content;
  }

  // Save if requested
  if (outputPath) {
    const fullContent = header + reviewContent;
    writeOutputFile(outputPath, fullContent);
  }
}
