import { existsSync, mkdirSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import type { RefInfo } from "./git.js";

// ---------------------------------------------------------------------------
// Timestamp formatting
// ---------------------------------------------------------------------------

/**
 * Format a unix timestamp (seconds) into a short local-time string.
 * Example: "Mar 16/26 3:30pm EDT"
 */
function formatTimestamp(unixSeconds: number): string {
  const date = new Date(unixSeconds * 1000);

  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const month = months[date.getMonth()];
  const day = date.getDate();
  const year = String(date.getFullYear()).slice(-2);

  let hours = date.getHours();
  const minutes = date.getMinutes();
  const ampm = hours >= 12 ? "pm" : "am";
  hours = hours % 12 || 12;

  const minuteStr = minutes === 0 ? "" : `:${String(minutes).padStart(2, "0")}`;

  // Get timezone abbreviation
  const tz = Intl.DateTimeFormat("en-US", { timeZoneName: "short" })
    .formatToParts(date)
    .find((p) => p.type === "timeZoneName")?.value ?? "";

  return `${month} ${day}/${year} ${hours}${minuteStr}${ampm} ${tz}`.trim();
}

/**
 * Build a parenthesized timestamp range string for two refs.
 * Example: "(Mar 12/26 12:32pm EDT → Mar 12/26 12:58pm EDT)"
 */
function formatTimestampRange(fromRef: RefInfo, toRef: RefInfo): string {
  if (!fromRef.timestamp || !toRef.timestamp) return "";
  return `(${formatTimestamp(fromRef.timestamp)} → ${formatTimestamp(toRef.timestamp)})`;
}

/**
 * Build a parenthesized single timestamp string for one ref.
 * Example: "(Mar 12/26 12:32pm EDT)"
 */
function formatSingleTimestamp(ref: RefInfo): string {
  if (!ref.timestamp) return "";
  return `(${formatTimestamp(ref.timestamp)})`;
}

// ---------------------------------------------------------------------------
// Markdown header generation
// ---------------------------------------------------------------------------

export function buildReleaseNotesHeader(
  fromRef: RefInfo,
  toRef: RefInfo,
  commitCount: number
): string {
  const today = new Date().toISOString().split("T")[0];
  const tsRange = formatTimestampRange(fromRef, toRef);
  const tsSuffix = tsRange ? ` ${tsRange}` : "";

  return `# Release Notes: ${fromRef.displayName} → ${toRef.displayName}${tsSuffix}

> Generated from commits after \`${fromRef.displayName}\` up to and including \`${toRef.displayName}\` (${commitCount} commits)
> Generated by git-genie on ${today}

`;
}

export function buildReviewHeader(
  startRef: RefInfo,
  endRef: RefInfo | null,
  commitCount: number
): string {
  const today = new Date().toISOString().split("T")[0];

  if (!endRef) {
    // Single commit
    const ts = formatSingleTimestamp(startRef);
    const tsSuffix = ts ? ` ${ts}` : "";
    return `# Code Review: ${startRef.displayName}${tsSuffix}

> Reviewing commit \`${startRef.displayName}\` (${commitCount} commit)
> Generated by git-genie on ${today}

`;
  }

  const tsRange = formatTimestampRange(startRef, endRef);
  const tsSuffix = tsRange ? ` ${tsRange}` : "";

  return `# Code Review: ${startRef.displayName}..${endRef.displayName}${tsSuffix}

> Reviewing commits \`${startRef.displayName}\` through \`${endRef.displayName}\` (inclusive, ${commitCount} commits)
> Generated by git-genie on ${today}

`;
}

// ---------------------------------------------------------------------------
// File output
// ---------------------------------------------------------------------------

export type OutputType = "release" | "review";

/**
 * Build the auto-generated filename for --save.
 */
export function buildSaveFilename(
  type: OutputType,
  targetRef: RefInfo
): string {
  const today = new Date().toISOString().split("T")[0];
  return `notes/${type}-${today}-${targetRef.displayName}.md`;
}

/**
 * Write markdown content to a file. Creates parent directories as needed.
 */
export function writeOutputFile(filePath: string, content: string): void {
  const resolved = resolve(filePath);
  const dir = dirname(resolved);

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  writeFileSync(resolved, content, "utf-8");
  console.error(`\nSaved to: ${resolved}`);
}

/**
 * Determine the output file path based on flags.
 * --output takes precedence over --save.
 */
export function resolveOutputPath(
  flags: { save?: boolean; output?: string },
  type: OutputType,
  targetRef: RefInfo
): string | null {
  if (flags.output) {
    return flags.output;
  }
  if (flags.save) {
    return buildSaveFilename(type, targetRef);
  }
  return null;
}
